{"name": "test_login", "status": "failed", "statusDetails": {"message": "AssertionError: assert 1 == 2", "trace": "self = <Tests.test_sample_allurereport_failedscreenshot_withclass.TestOne object at 0x0000021BCB3E7940>\n\n    def test_login(self):\n        global driver\n        logger = self.getLogger()\n        logger.info(\"This is sample log\")\n        driver = self.driver\n>       assert 1==2\nE       assert 1 == 2\n\ntest_sample_allurereport_failedscreenshot_withclass.py:33: AssertionError"}, "attachments": [{"name": "log", "source": "42eb5a87-1c9a-4782-83ec-cca5a1f58644-attachment.txt", "type": "text/plain"}], "start": 1657700779416, "stop": 1657700779643, "uuid": "b396d435-c79d-4ee5-b131-9d556006adb7", "historyId": "2abffc522ad19c33fa1c8bd30cdc61d9", "testCaseId": "0f79da59d095a8c57e8fcd186a703283", "fullName": "test_sample_allurereport_failedscreenshot_withclass.TestOne#test_login", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('setup')"}, {"name": "suite", "value": "test_sample_allurereport_failedscreenshot_withclass"}, {"name": "subSuite", "value": "TestOne"}, {"name": "host", "value": "LAPTOP-A66B7O37"}, {"name": "thread", "value": "22368-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_sample_allurereport_failedscreenshot_withclass"}]}